#!/usr/bin/env sh

echo $DOCKER_REPO
namespace=$(echo $DOCKER_REPO | grep -Po '\/([^/]+)\/' | grep -Po '[^/]+')
echo $namespace
if [ "$DOCKER_TAG" = "dev-nightly" ]
then
    export HOST_TAG="dev"
fi

docker build . -t $IMAGE_NAME --build-arg NAMESPACE=$namespace --build-arg HOST_TAG=$HOST_TAG