#!/usr/bin/env sh

export $(cat ../../.env | xargs)

if [ "$DOCKER_TAG" = "$CURRENT_HOST_VERSION" ]; then
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker tag $IMAGE_NAME $DOCKER_REPO:2.0
    docker push $DOCKER_REPO:latest
    docker push $DOCKER_REPO:2.0
fi