#!/usr/bin/env sh

if [ "$DOCKER_TAG" = "v2.0.11776-alpha" ]; then
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker tag $IMAGE_NAME $DOCKER_REPO:2.0
    docker push $DOCKER_REPO:latest
    docker push $DOCKER_REPO:2.0
fi