name: kudulite.$(Date:yyyyMMdd).$(Rev:r)

pr:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

jobs:
- job: LoginACR
  displayName: Login to ACR Registry
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - bash: |
        set -e
        echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
      continueOnError: false
      env:
        pswd: $(dockerPassword)
