queue: Hosted Ubuntu 1604
trigger: none

steps:
- bash: |
    echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
  displayName: login
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    export ReleaseVersion=$(ReleaseVersion)
    export tag=dev
    ./kudulite/tag.sh
  displayName: tag and push images
  continueOnError: false