queue: Hosted Ubuntu 1604
trigger: none
variables:
  dockerId: azurefunctions

steps:
- bash: |
    echo $pswd | docker login -u $(dockerId) --password-stdin $(dockerId).azurecr.io
  displayName: login
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    set -e
    REGISTRY=azurefunctions.azurecr.io/public/azure-functions/
    RELEASE_VERSION=$(ReleaseVersion)
    if [[ "$IMAGE_TAG_VERSION" == 2\.0\.* ]]; then
      MAJOR_VERSION=2.0
    elif [[ "$IMAGE_TAG_VERSION" == 3\.0\.* ]]; then
      MAJOR_VERSION=3.0
    fi

    echo "##vso[task.setvariable variable=REGISTRY]$REGISTRY"
    echo "##vso[task.setvariable variable=RELEASE_VERSION]$RELEASE_VERSION"
    echo "##vso[task.setvariable variable=MAJOR_VERSION]$MAJOR_VERSION"
  displayName: set env
  continueOnError: false

- bash: |
    ./build/dotnet.sh tag_push
  displayName: tag and push dotnet images
  continueOnError: false

- bash: |
    ./build/java.sh tag_push
  displayName: tag and push java images
  continueOnError: false

- bash: |
    ./build/node.sh tag_push
  displayName: tag and push node images
  continueOnError: false

- bash: |
    ./build/powershell.sh tag_push
  displayName: tag and push powershell images
  continueOnError: false

- bash: |
    ./build/python.sh tag_push
  displayName: tag and push python images
  continueOnError: false
