pool:
    vmImage: 'Ubuntu-latest'

pr:
  branches:
    include:
      - dev
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/base/*
      - host/4/bullseye/amd64/java/java8/*
      - host/4/bullseye/amd64/java/java11/*

trigger:
  branches:
    include:
      - dev
      - refs/tags/4.*
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/base/*
      - host/4/bullseye/amd64/java/java8/*
      - host/4/bullseye/amd64/java/java11/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      cp host/mvn-entrypoint.sh host/4/bullseye/amd64/java/java8
      cp host/mvn-entrypoint.sh host/4/bullseye/amd64/java/java11
      cp host/settings-docker.xml host/4/bullseye/amd64/java/java8
      cp host/settings-docker.xml host/4/bullseye/amd64/java/java11

  - bash: |
      ./host/generate-composite.sh -4 java

    displayName: create java-appservice dockerfiles
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java8
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/java/java8/java8.Dockerfile \
                  host/4/bullseye/amd64/java/java8
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java8-slim
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/java/java8/java8-slim.Dockerfile \
                  host/4/bullseye/amd64/java/java8
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java8-appservice
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/out/java/java8-appservice.Dockerfile \
                  host/4/bullseye/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java8.1-appservice
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/out/java/java8-zulu-appservice.Dockerfile \
                  host/4/bullseye/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8.1-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java8-build
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/java/java8/java8-build.Dockerfile \
                  host/4/bullseye/amd64/java/java8
      docker push $IMAGE_NAME
    displayName: java8-build
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java11

      docker build -t $IMAGE_NAME \
                -f host/4/bullseye/amd64/java/java11/java11.Dockerfile \
                host/4/bullseye/amd64/java/java11
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java11-slim
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/java/java11/java11-slim.Dockerfile \
                  host/4/bullseye/amd64/java/java11
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java11-appservice
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/out/java/java11-appservice.Dockerfile \
                  host/4/bullseye/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java11.1-appservice
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/out/java/java11-zulu-appservice.Dockerfile \
                  host/4/bullseye/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11.1-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/java:$(Build.SourceBranchName)-java11-build
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/java/java11/java11-build.Dockerfile \
                  host/4/bullseye/amd64/java/java11
      docker push $IMAGE_NAME
    displayName: java11-build
    continueOnError: false
