name: Nightly-Build
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - dev
  always: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: dev
        fetch-depth: 0
        token: ${{ secrets.PIPELINE_ADMIN }}
    - name: Update Nightly with Latest Dev
      id: createBranch
      run: |
        set -e
        git config --local user.email "azfuncgh@github.com"
        git config --local user.name "Azure Functions"
        git fetch --all
        git checkout -b  nightly-build origin/nightly-build
        git merge dev
        git push origin nightly-build
      env:
        GITHUB_TOKEN: ${{ secrets.PIPELINE_ADMIN }}