queue: Hosted Ubuntu 1804

pr:
  branches:
    include:
      - dev
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/node/*

trigger:
  branches:
    include:
      - dev
      - refs/tags/4.*
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/node/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)
    
  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/node:$(Build.SourceBranchName)-node14

      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/node/node14/node14.Dockerfile \
                  host/4/bullseye/amd64/node/node14
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/node:$(Build.SourceBranchName)-node14-slim

      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/node/node14/node14-slim.Dockerfile \
                  host/4/bullseye/amd64/node/node14/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/node:$(Build.SourceBranchName)-node14-appservice

      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/node/node14/node14-appservice.Dockerfile \
                  host/4/bullseye/amd64/node/node14/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14-appservice
    continueOnError: false
