queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - dev
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/powershell/*

trigger:
  branches:
    include:
      - dev
      - refs/tags/4.*
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/powershell/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/powershell:$(Build.SourceBranchName)-powershell7

      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/powershell/powershell7.Dockerfile \
                  host/4/bullseye/amd64/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/powershell:$(Build.SourceBranchName)-powershell7-slim
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/powershell/powershell7-slim.Dockerfile \
                  host/4/bullseye/amd64/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/4/powershell:$(Build.SourceBranchName)-powershell7-appservice
      docker build -t $IMAGE_NAME \
                  -f host/4/bullseye/amd64/powershell/powershell7-appservice.Dockerfile \
                  host/4/bullseye/amd64/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7-appservice
    continueOnError: false
