trigger: none
# Publish pipelines are triggered via HTTP method in release pipeline. See [App Service] v4 stage release
pool:
    vmImage: 'Ubuntu-latest'

steps:
  - bash: |
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
    displayName: login
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      SOURCE_REGISTRY=azurefunctions.azurecr.io/azure-functions/4
      TARGET_REGISTRY=azurefunctions.azurecr.io/public/azure-functions

      if [ -z "$(TargetVersion)" ]; then
        echo "ERROR: TargetVersion is required"
        exit 1
      fi

      if [ -z "$(PrivateVersion)" ]; then
        echo "ERROR: PrivateVersion is required"
        exit 1
      fi

      if [ -z "$(StageNumber)" ]; then
        echo "ERROR: StageNumber is required"
        exit 1
      fi

      echo "##vso[task.setvariable variable=SOURCE_REGISTRY]$SOURCE_REGISTRY"
      echo "##vso[task.setvariable variable=TARGET_REGISTRY]$TARGET_REGISTRY"
    displayName: set env
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice

      docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice $TARGET_REGISTRY/dotnet:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/dotnet:$(PrivateVersion)-appservice $TARGET_REGISTRY/dotnet:$(TargetVersion)-dotnet6-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/dotnet:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/dotnet:$(TargetVersion)-dotnet6-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push dotnet images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated6.0-appservice

      docker tag $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated6.0-appservice $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated6.0-appservice $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated6.0-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated6.0-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push dotnet-isolated images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated7.0-appservice

      docker tag $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated7.0-appservice $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated7.0-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated7.0-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push dotnet-isolated7 images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated8.0-appservice

      docker tag $SOURCE_REGISTRY/dotnet-isolated:$(PrivateVersion)-dotnet-isolated8.0-appservice $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated8.0-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/dotnet-isolated:$(TargetVersion)-dotnet-isolated8.0-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push dotnet-isolated8 images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java8-appservice
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-appservice
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java17-appservice
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java21-appservice

      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java8-appservice $TARGET_REGISTRY/java:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java8-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java8-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java17-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java17-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java21-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java21-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/java:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java8-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java17-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java21-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push java images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/node:$(PrivateVersion)-node14-appservice

      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node14-appservice $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node14-appservice $TARGET_REGISTRY/node:$(TargetVersion)-node14-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/node:$(TargetVersion)-node14-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push node images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/node:$(PrivateVersion)-node16-appservice

      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node16-appservice $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node16-appservice $TARGET_REGISTRY/node:$(TargetVersion)-node16-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/node:$(TargetVersion)-node16-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push node images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/node:$(PrivateVersion)-node18-appservice

      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node18-appservice $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node18-appservice $TARGET_REGISTRY/node:$(TargetVersion)-node18-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/node:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/node:$(TargetVersion)-node18-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push node images
    continueOnError: false
  
  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/node:$(PrivateVersion)-node20-appservice

      docker tag $SOURCE_REGISTRY/node:$(PrivateVersion)-node20-appservice $TARGET_REGISTRY/node:$(TargetVersion)-node20-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/node:$(TargetVersion)-node20-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push node images
    continueOnError: false


  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/powershell:$(PrivateVersion)-powershell7.2-appservice
      docker pull $SOURCE_REGISTRY/powershell:$(PrivateVersion)-powershell7.4-appservice

      docker tag $SOURCE_REGISTRY/powershell:$(PrivateVersion)-powershell7.2-appservice $TARGET_REGISTRY/powershell:$(TargetVersion)-powershell7.2-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/powershell:$(PrivateVersion)-powershell7.4-appservice $TARGET_REGISTRY/powershell:$(TargetVersion)-powershell7.4-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/powershell:$(TargetVersion)-powershell7.2-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/powershell:$(TargetVersion)-powershell7.4-appservice-stage$(StageNumber)
      docker system prune -a -f
    displayName: tag and push powershell images
    continueOnError: false

  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.7-appservice
      docker pull $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.8-appservice
      docker pull $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.9-appservice
      docker pull $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.10-appservice
      docker pull $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.11-appservice

      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.7-appservice $TARGET_REGISTRY/python:$(TargetVersion)-python3.7-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.8-appservice $TARGET_REGISTRY/python:$(TargetVersion)-python3.8-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.9-appservice $TARGET_REGISTRY/python:$(TargetVersion)-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.9-appservice $TARGET_REGISTRY/python:$(TargetVersion)-python3.9-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.10-appservice $TARGET_REGISTRY/python:$(TargetVersion)-python3.10-appservice-stage$(StageNumber)
      docker tag $SOURCE_REGISTRY/python:$(PrivateVersion)-python3.11-appservice $TARGET_REGISTRY/python:$(TargetVersion)-python3.11-appservice-stage$(StageNumber)

      docker push $TARGET_REGISTRY/python:$(TargetVersion)-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/python:$(TargetVersion)-python3.7-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/python:$(TargetVersion)-python3.8-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/python:$(TargetVersion)-python3.9-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/python:$(TargetVersion)-python3.10-appservice-stage$(StageNumber)
      docker push $TARGET_REGISTRY/python:$(TargetVersion)-python3.11-appservice-stage$(StageNumber)

      docker system prune -a -f
    displayName: tag and push python images
    continueOnError: false
