pool:
  vmImage: "Ubuntu-latest"

pr:
  branches:
    include:
      - dev
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/base/*
      - host/4/bullseye/amd64/python/*
      - host/4/python-build.yml

trigger:
  branches:
    include:
      - dev
      - refs/tags/4.*
      - release/4.x
  paths:
    include:
      - host/4/bullseye/amd64/base/*
      - host/4/bullseye/amd64/python/*
      - host/4/python-build.yml

variables:
  HOST_MAJOR_VERSION: 4
  DOCKER_BUILDKIT: 1

jobs:
  - job: Python
    strategy:
      matrix:
        _37:
          pythonVersion: "3.7"
          pythonImageNameSuffix: "37"
        _38:
          pythonVersion: "3.8"
          pythonImageNameSuffix: "38"
        _39:
          pythonVersion: "3.9"
          pythonImageNameSuffix: "39"
        _310:
          pythonVersion: "3.10"
          pythonImageNameSuffix: "310"
    steps:
      - bash: |
          # login
          set -e
          echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
        displayName: login to registry
        continueOnError: false
        env:
          pswd: $(dockerPassword)
      - bash: |
          ./host/generate-composite.sh -$(HOST_MAJOR_VERSION) python
        displayName: create python-appservice dockerfiles
        continueOnError: false
      - bash: |
          set -e
          IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/$(HOST_MAJOR_VERSION)/python:$(Build.SourceBranchName)-python$(pythonVersion)
          docker build -t $IMAGE_NAME \
                      -f host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)/python$(pythonImageNameSuffix).Dockerfile \
                      host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)
          npm run test $IMAGE_NAME --prefix test/
          docker push $IMAGE_NAME
        displayName: python
        continueOnError: false
      - bash: |
          set -e
          IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/$(HOST_MAJOR_VERSION)/python:$(Build.SourceBranchName)-python$(pythonVersion)-slim
          docker build -t $IMAGE_NAME \
                      -f host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)/python$(pythonImageNameSuffix)-slim.Dockerfile \
                      host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)/
          npm run test $IMAGE_NAME --prefix test/
          docker push $IMAGE_NAME
        displayName: python-slim
        continueOnError: false
      - bash: |
          set -e
          IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/$(HOST_MAJOR_VERSION)/python:$(Build.SourceBranchName)-python$(pythonVersion)-appservice
          docker build -t $IMAGE_NAME \
                      -f host/$(HOST_MAJOR_VERSION)/bullseye/amd64/out/python/python$(pythonImageNameSuffix)-appservice.Dockerfile \
                      host/$(HOST_MAJOR_VERSION)/bullseye/amd64/out/python/
          npm run test $IMAGE_NAME --prefix test/
          docker push $IMAGE_NAME
        displayName: python-appservice
        continueOnError: false
      - bash: |
          set -e
          IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/$(HOST_MAJOR_VERSION)/python:$(Build.SourceBranchName)-python$(pythonVersion)-buildenv
          docker build -t $IMAGE_NAME \
                      -f host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)/python$(pythonImageNameSuffix)-buildenv.Dockerfile \
                      host/$(HOST_MAJOR_VERSION)/bullseye/amd64/python/python$(pythonImageNameSuffix)/
          docker push $IMAGE_NAME
        displayName: python-buildenv
        continueOnError: false
