#!/usr/bin/env sh

echo $DOCKER_REPO
namespace=$(echo $DOCKER_REPO | grep -Po '\/([^/]+)\/' | grep -Po '[^/]+')
echo $namespace

if [ "$DOCKER_TAG" = "v2.0.11737-alpha" ]; then
    LATEST_TAG="-t $DOCKER_REPO:latest"
fi

docker build . -t $IMAGE_NAME $(echo $LATEST_TAG) --build-arg NAMESPACE=$namespace --build-arg HOST_TAG=$DOCKER_TAG