queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - host/2.0/stretch/amd64/java/*
      - host/2.0/alpine/amd64/java/*

trigger:
  branches:
    include:
      - dev
      - refs/tags/2.0.*
  paths:
    include:
      - host/2.0/stretch/amd64/java/*
      - host/2.0/alpine/amd64/java/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/2.0/java:$(Build.SourceBranchName)-java8-appservice
      docker build -t $IMAGE_NAME \
                  -f host/2.0/stretch/amd64/java/java8-appservice.Dockerfile \
                  host/2.0/stretch/amd64/java/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-appservice
    continueOnError: false
