queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/2.0/stretch/arm32v7/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - host/2.0/stretch/arm32v7/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

      docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: register qemu
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/dotnet:$(Build.SourceBranchName)-bionic-arm32v7

      docker build -t $IMAGE_NAME \
                  -f host/2.0/bionic/arm32v7/dotnet/dotnet.Dockerfile \
                  host/2.0/bionic/arm32v7/dotnet/
      npm run test $IMAGE_NAME --prefix test/
      docker push $IMAGE_NAME
    displayName: dotnet bionic arm32v7
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node8-bionic-arm32v7

      docker build -t $IMAGE_NAME \
                  -f host/2.0/bionic/arm32v7/node/node8.Dockerfile \
                  host/2.0/bionic/arm32v7/node/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node8 bionic arm32v7
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell6-bionic-arm32v7

      docker build -t $IMAGE_NAME \
                  -f host/2.0/bionic/arm32v7/powershell/powershell6.Dockerfile \
                  host/2.0/bionic/arm32v7/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell6 bionic arm32v7
    continueOnError: false
