queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/2.0-upgrade/stretch/amd64/dotnet/*

trigger:
  branches:
    include:
      - master
      - refs/tags/3.0.*
  paths:
    include:
      - host/2.0-upgrade/stretch/amd64/dotnet/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $dockerUsername --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)
      dockerUsername: $(dockerUsername)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/2.0/dotnet:$(Build.SourceBranchName)-upgrade-appservice

      docker build -t $IMAGE_NAME \
                  -f host/2.0-upgrade/stretch/amd64/dotnet/dotnet-appservice.Dockerfile \
                  host/2.0-upgrade/stretch/amd64/dotnet/
      npm run test $IMAGE_NAME --prefix test/
      docker push $IMAGE_NAME

    displayName: dotnet build
    continueOnError: false