queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/java/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/java/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8.Dockerfile \
                  host/3.0/buster/amd64/java/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-slim
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8-slim.Dockerfile \
                  host/3.0/buster/amd64/java/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-appservice
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8-appservice.Dockerfile \
                  host/3.0/buster/amd64/java/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-core-tools
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8-core-tools.Dockerfile \
                  host/3.0/buster/amd64/java/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-core-tools
    continueOnError: false

