pool:
    vmImage: 'Ubuntu-latest'

pr:
  branches:
    include:
      - dev
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/java/java8/*
      - host/3.0/buster/amd64/java/java11/*
      - host/3.0/java-build.yml

trigger:
  branches:
    include:
      - dev
      - refs/tags/3.*.*
      - refresh/3.*
      - release/3.x

variables:
- name: image_list
  value: ''

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      cp host/mvn-entrypoint.sh host/3.0/buster/amd64/java/java8
      cp host/mvn-entrypoint.sh host/3.0/buster/amd64/java/java11
      cp host/settings-docker.xml host/3.0/buster/amd64/java/java8
      cp host/settings-docker.xml host/3.0/buster/amd64/java/java11

  - bash: |
      ./host/generate-composite.sh -3 java

    displayName: create java-appservice dockerfiles
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_NAME"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8/java8.Dockerfile \
                  host/3.0/buster/amd64/java/java8
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-slim
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8/java8-slim.Dockerfile \
                  host/3.0/buster/amd64/java/java8
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-appservice
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/java/java8-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-build
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8/java8-build.Dockerfile \
                  host/3.0/buster/amd64/java/java8
      docker push $IMAGE_NAME
    displayName: java8-build
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"


      docker build -t $IMAGE_NAME \
                -f host/3.0/buster/amd64/java/java11/java11.Dockerfile \
                host/3.0/buster/amd64/java/java11
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11-slim
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java11/java11-slim.Dockerfile \
                  host/3.0/buster/amd64/java/java11
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11-appservice
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"
      
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/java/java11-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/java
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11-build
      IMAGE_ARRAY="$(image_list),$IMAGE_NAME"
      echo "##vso[task.setvariable variable=image_list;]$IMAGE_ARRAY"

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java11/java11-build.Dockerfile \
                  host/3.0/buster/amd64/java/java11
      docker push $IMAGE_NAME
    displayName: java11-build
    continueOnError: false

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Manifest Generator'
    inputs:
      BuildDropPath: host
      Verbosity: Verbose
      DockerImagesToScan: $(image_list)

  - task: PublishPipelineArtifact@1
    displayName: 'Publish SBOM Artifact'
    inputs:
      targetPath: host/_manifest
      artifact: SBOM-Functionsv3-Java-$(Build.SourceBranchName)