pool:
    name: '1ES-Hosted-Azure-Functions'
    demands:
      - ImageOverride -equals MMSUbuntu20.04TLS

pr:
  branches:
    include:
      - dev
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/java/java8/*
      - host/3.0/buster/amd64/java/java11/*

trigger:
  branches:
    include:
      - dev
      - refs/tags/3.*.*
      - u/clink/exec_SBOM_test
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/java/java8/*
      - host/3.0/buster/amd64/java/java11/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      ./host/generate-composite.sh -3 java

    displayName: create java-appservice dockerfiles
    continueOnError: false

  - bash: |
      mkdir -p "$(System.ArtifactsDirectory)/_SBOM"
      mkdir -p "$(System.ArtifactsDirectory)/_docker"

    displayName: Create SBOM Directories
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8/java8.Dockerfile \
                  host/3.0/buster/amd64/java/java8 | tee $(System.ArtifactsDirectory)/_docker/DOCKER0.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-slim
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java8/java8-slim.Dockerfile \
                  host/3.0/buster/amd64/java/java8 | tee $(System.ArtifactsDirectory)/_docker/DOCKER1.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java8-appservice
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/java/java8-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/java | tee $(System.ArtifactsDirectory)/_docker/DOCKER2.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java8-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11

      docker build -t $IMAGE_NAME \
                -f host/3.0/buster/amd64/java/java11/java11.Dockerfile \
                host/3.0/buster/amd64/java/java11 | tee $(System.ArtifactsDirectory)/_docker/DOCKER3.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11-slim
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/java/java11/java11-slim.Dockerfile \
                  host/3.0/buster/amd64/java/java11 | tee $(System.ArtifactsDirectory)/_docker/DOCKER4.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/java:$(Build.SourceBranchName)-java11-appservice
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/java/java11-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/java | tee $(System.ArtifactsDirectory)/_docker/DOCKER5.DOCKEROUTPUT
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: java11-appservice
    continueOnError: false

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'SBOM Generation Task'
    condition: succeeded()
  # What do we do for this?  There is no output directory - it is a container build
    inputs:
      BuildDropPath: host/3.0/buster/amd64/java/java8
      Verbosity: Verbose
      DockerImagesToScan: 12345

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: host/3.0/buster/amd64/java/java8
      artifact: MyArtifact
