pool:
  vmImage: "windows-2019"

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/nanoserver/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/nanoserver/*

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
  - powershell: |
      # login
      docker login -u "$(dockerUsername)" --password "$(dockerPassword)" azurefunctions.azurecr.io
    displayName: login
    errorActionPreference: stop

  - powershell: |
      $IMAGE_NAME="azurefunctions.azurecr.io/azure-functions/dotnet:$(Build.SourceBranchName)-nanoserver-1809"

      docker build -t $IMAGE_NAME `
                  -f host/3.0/nanoserver/1809/dotnet.Dockerfile `
                  host/3.0/nanoserver/1809/
      # The runtime images don't run on azure devops due to:
      #   The container operating system does not match the host operating system.
      # cd test
      # npm install --silent --log-level=error
      # npm run test-win $IMAGE_NAME
      docker push $IMAGE_NAME
    displayName: build dotnet nanoserver 1809
    errorActionPreference: stop
  # - powershell: |
  #     $IMAGE_NAME="azurefunctions.azurecr.io/azure-functions/dotnet:$(Build.SourceBranchName)-nanoserver-1903"
  #     docker build -t $IMAGE_NAME `
  #                 -f host/3.0/nanoserver/1903/dotnet.Dockerfile `
  #                 host/3.0/nanoserver/1903/
  #     # The runtime images don't run on azure devops due to:
  #     #   The container operating system does not match the host operating system.
  #     # cd test
  #     # npm install --silent --log-level=error
  #     # npm run test-win $IMAGE_NAME
  #     docker push $IMAGE_NAME
  #   displayName: build dotnet nanoserver 1903
  #   errorActionPreference: stop
  # - powershell: |
  #     $IMAGE_NAME="azurefunctions.azurecr.io/azure-functions/dotnet:$(Build.SourceBranchName)-nanoserver-1909"
  #     docker build -t $IMAGE_NAME `
  #                 -f host/3.0/nanoserver/1909/dotnet.Dockerfile `
  #                 host/3.0/nanoserver/1909/
  #     # The runtime images don't run on azure devops due to:
  #     #   The container operating system does not match the host operating system.
  #     # cd test
  #     # npm install --silent --log-level=error
  #     # npm run test-win $IMAGE_NAME
  #     docker push $IMAGE_NAME
  #   displayName: build dotnet nanoserver 1909
  #   errorActionPreference: stop
