pool:
    vmImage: 'Ubuntu-latest'

pr:
  branches:
    include:
      - dev
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/node/*
      - host/3.0/node-build.yml

trigger:
  branches:
    include:
      - dev
      - refs/tags/3.*.*
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/node/*
      - host/3.0/node-build.yml

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      ./host/generate-composite.sh -3 node

    displayName: create node-appservice dockerfiles
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node8-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/node/node8-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/node/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node8-appservice
    continueOnError: false    
    
  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node10

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node10/node10.Dockerfile \
                  host/3.0/buster/amd64/node/node10
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node10
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node10-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node10/node10-slim.Dockerfile \
                  host/3.0/buster/amd64/node/node10/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node10-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node10-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/node/node10-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/node/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node10-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node12

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node12/node12.Dockerfile \
                  host/3.0/buster/amd64/node/node12
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node12
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node12-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node12/node12-slim.Dockerfile \
                  host/3.0/buster/amd64/node/node12/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node12-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node12-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/node/node12-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/node/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node12-appservice
    continueOnError: false
    
  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node14

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node14/node14.Dockerfile \
                  host/3.0/buster/amd64/node/node14
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node14-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/node/node14/node14-slim.Dockerfile \
                  host/3.0/buster/amd64/node/node14/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/node:$(Build.SourceBranchName)-node14-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/node/node14-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/node/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: node14-appservice
    continueOnError: false
