pool:
    vmImage: 'Ubuntu-latest'
    
pr:
  branches:
    include:
      - dev
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/powershell/powershell6/*
      - host/3.0/buster/amd64/powershell/powershell7/*
      - host/3.0/powershell-build.yml
      

trigger:
  branches:
    include:
      - dev
      - refs/tags/3.*.*
      - release/3.x
  paths:
    include:
      - host/3.0/buster/amd64/base/*
      - host/3.0/buster/amd64/powershell/powershell6/*
      - host/3.0/buster/amd64/powershell/powershell7/*
      - host/3.0/powershell-build.yml

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      ./host/generate-composite.sh -3 powershell

    displayName: create powershell-appservice dockerfiles
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell6

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/powershell/powershell6/powershell6.Dockerfile \
                  host/3.0/buster/amd64/powershell/powershell6
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell6
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell6-slim
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/powershell/powershell6/powershell6-slim.Dockerfile \
                  host/3.0/buster/amd64/powershell/powershell6/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell6-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell6-appservice
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/powershell/powershell6-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell6-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell7

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/powershell/powershell7/powershell7.Dockerfile \
                  host/3.0/buster/amd64/powershell/powershell7/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell7-slim
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/powershell/powershell7/powershell7-slim.Dockerfile \
                  host/3.0/buster/amd64/powershell/powershell7/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/powershell:$(Build.SourceBranchName)-powershell7-appservice
      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/out/powershell/powershell7-appservice.Dockerfile \
                  host/3.0/buster/amd64/out/powershell/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: powershell7-appservice
    continueOnError: false
