queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/python/python38/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/python/python38/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.6

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python36/python36.Dockerfile \
                  host/3.0/buster/amd64/python/python36
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.6
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.6-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python36/python36-slim.Dockerfile \
                  host/3.0/buster/amd64/python/python36/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.6-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.6-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python36/python36-appservice.Dockerfile \
                  host/3.0/buster/amd64/python/python36/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.6-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.6-buildenv

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python36/python36-buildenv.Dockerfile \
                  host/3.0/buster/amd64/python/python36/
      docker push $IMAGE_NAME
    displayName: python3.6-buildenv
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.7

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python37/python37.Dockerfile \
                  host/3.0/buster/amd64/python/python37
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.7
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.7-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python37/python37-slim.Dockerfile \
                  host/3.0/buster/amd64/python/python37/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.7-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.7-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python37/python37-appservice.Dockerfile \
                  host/3.0/buster/amd64/python/python37/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.7-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.7-buildenv

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python37/python37-buildenv.Dockerfile \
                  host/3.0/buster/amd64/python/python37/
      docker push $IMAGE_NAME
    displayName: python3.7-buildenv
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38.Dockerfile \
                  host/3.0/buster/amd64/python/python38
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.8
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8-slim

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38-slim.Dockerfile \
                  host/3.0/buster/amd64/python/python38/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.8-slim
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8-appservice

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38-appservice.Dockerfile \
                  host/3.0/buster/amd64/python/python38/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.8-appservice
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8-buildenv

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38-buildenv.Dockerfile \
                  host/3.0/buster/amd64/python/python38/
      docker push $IMAGE_NAME
    displayName: python3.8-buildenv
    continueOnError: false

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8-core-tools

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38-buildenv.Dockerfile \
                  host/3.0/buster/amd64/python/python38/
      docker push $IMAGE_NAME
    displayName: python3.8-core-tools
    continueOnError: false
