name: Re-Fresh Non-appservice Images
on:
  workflow_dispatch:
    inputs:
      targetTag:
        description: 'Tag to re-fresh (e.g. 4.9.0)'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: dev
        fetch-depth: 0
        token: ${{ secrets.PIPELINE_ADMIN }}
    - name: Create Rebuild Branch
      id: createBranch
      run: |
        set -e
        git config --local user.email "azfuncgh@github.com"
        git config --local user.name "Azure Functions"
        git fetch --all
        git push origin --delete "refresh/${{ github.event.inputs.targetTag }}-refresh" &>/dev/null 
        git checkout ${{ github.event.inputs.targetTag }}
        git checkout -b "refresh/${{ github.event.inputs.targetTag }}-refresh"
        cd host
        ./verify-republish-pipeline.sh ${{ github.event.inputs.targetTag }}
        git push origin "refresh/${{ github.event.inputs.targetTag }}-refresh"
      env:
        GITHUB_TOKEN: ${{ secrets.PIPELINE_ADMIN }} 