name: Refresh Non-appservice Images

on:
  repository_dispatch:
    types: [refresh]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: dev
        fetch-depth: 0
        token: ${{ secrets.PIPELINE_ADMIN }}
    - name: Create Rebuild Branch
      id: createBranch
      run: |
        set -e
        git config --local user.email "azfuncgh@github.com"
        git config --local user.name "Azure Functions"
        git fetch --all
        git checkout ${{ github.event.client_payload.targetTag }}
        date > refresh-time.txt
        git add refresh-time.txt
        git commit -m "Refresh Images for ${{ github.event.client_payload.targetTag }}"
        git checkout -b "refresh/${{ github.event.client_payload.targetTag }}-refresh"
        cd host
        ./verify-republish-pipeline.sh ${{ github.event.client_payload.targetTag }}
        git push origin "refresh/${{ github.event.client_payload.targetTag }}-refresh" --force
      env:
        GITHUB_TOKEN: ${{ secrets.PIPELINE_ADMIN }} 