name: Refresh Non-appservice Images
on:
  workflow_dispatch:
    inputs:
      targetTag:
        description: 'Tag to refresh (e.g. 4.9.0)'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: dev
        fetch-depth: 0
        token: ${{ secrets.PIPELINE_ADMIN }}
    - name: Create Rebuild Branch
      id: createBranch
      run: |
        set -e
        git config --local user.email "azfuncgh@github.com"
        git config --local user.name "Azure Functions"
        git fetch --all
        git checkout ${{ github.event.inputs.targetTag }}
        date > refresh-time.txt
        git add refresh-time.txt
        git commit -m "Refresh Images for ${{ github.event.inputs.targetTag }}"
        fullversion=${{ github.event.inputs.targetTag }}
        majorversion=${fullversion:0:1}
        git checkout -b "refresh/${majorversion}-refresh"
        cd host
        ./verify-republish-pipeline.sh ${{ github.event.inputs.targetTag }}
        git push origin "refresh/${majorversion}-refresh" --force
      env:
        GITHUB_TOKEN: ${{ secrets.PIPELINE_ADMIN }} 